dist: xenial
language: cpp

compiler:
  - gcc
    # temporarily disabled clang because travis runs out of memory when running the coverage build
    # - clang

before_install:
  - sudo apt-get install -y lcov python-yaml
  - sudo pip install codecov

before_script:
  - wget https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz
  - tar xzf v1.1.0.tar.gz
  - cd rapidjson-1.1.0
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON ..

script:
  - make
  - make test
  - make serialize-test-coverage

after_success:
  - codecov -X gcov
